dataset:
  hdf5_paths:
  - ../../data/metaworld/pre-training/drawer-open.hdf5
  batch_size: 16
  num_workers: 8
  pin_memory: true
  train_ratio: 0.96
  seed: 42
  views:
  - cam0
  - cam1
  - cam2
  - cam3
  - cam4
  - cam5
  train_temporal_strides:
  - 3
  - 6
  - 9
  validation_temporal_stride: 9

vit:
  patch_size: 16
  in_chans: 3
  embed_dim: 128
  depth: 8
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: true
  dropout: 0.0
  attn_dropout: 0.0
  drop_path_rate: 0.1
  layerscale_init: 1.0
model:
  state_dim: 256
  temporal_modeling: false
  masking:
    inv_tube_mask_ratio: 0.5
    tube_mask_per_view: true
    flow_patch_threshold_pixels: 0.5
  decoder:
    num_parent_tokens: 256
    gaussians_per_parent: 8
    global_center:
      - 0.0
      - 0.5
      - 0.1
    anchor_init_std: 0.15
    parent_offset_scale: 0.1
    child_radius: 0.05
    dim: 128
    depth: 2
    num_heads: 4
    mlp_ratio: 4.0
  motion:
    translation_max: 0.5
gaussian:
  max_sh_degree: 1
  scale_min:
  - 0.0005
  - 0.0005
  - 0.0005
  scale_max:
  - 0.05
  - 0.05
  - 0.05
  scale_scale: 0.05
  scale_bias: -1.5
  rotation_scale: 1.0
  rotation_bias: 0.0
  opacity_scale: 1.0
  opacity_bias: 0.0
  color_scale: 1.0
  color_bias: 0.0
  sh_rest_scale: 0.1
  sh_rest_raw_scale: 1.0
  sh_rest_raw_bias: 0.0
renderer:
  znear: 0.1
  zfar: 2.0
  white_background: false
train:
  num_epochs: 100
  max_global_steps: 300000
  lr: 5.0e-4
  lr_schedule: cosine
  lr_warmup_steps: 10000
  min_lr: 1.0e-4
  temporal_anchor: "t0"
  temporal_loss_ramp_steps: 20000
  flow_weight: 0.1
  flow_alpha_threshold: 0.01
  flow_smooth_l1_beta: 1.0
  dynamic_region_weight: 1.0
  visibility_weight: 10.0
  device: cuda
  use_segmentation_mask: false
  rec_weight: 1.0
  ssim_weight: 0.2
  silhouette_weight: 0.0
  global_depth_weight: 1.0
  hard_depth_weight: 1.0
  soft_depth_weight: 1.0
  hard_depth_opacity: 0.95
  local_depth_weight: 0.75
  local_depth_min_patch_size: 8
  local_depth_max_patch_size: 32
  local_depth_min_valid_pixels: 16
  inv_contrastive_weight: 1.0
  inv_consistency_weight: 0.5
  temperature: 0.1
  scalar_log_every: 250
  val_num_batches: 2
  eval_every: 1000
  save_every: 10000
  ckpt_dir: ./checkpoints/metaworld/encoders/SplatterVAE-single-timestep-no-segmentation-mask/drawer-open/grouped-gaussian-set/
  resume_from_last: false
  val_pointcloud_max_points: 4096
wandb:
  enabled: true
  project: metaworld-SplatterVAE
  entity: null
  run_name: metaworld-drawer-open-single-timestep-grouped-gaussian-set-no-segmentation-mask
  tags:
  - single-timestep-state-bottleneck
  - no-dense-motion
  - waft-guided-masking
  - t0-only-rendering
  - diverse-demo-collection
  - invariant-only
  - grouped-gaussian-set
  - no-segmentation-mask
  - parent-anchor
