output:
  path: /home/ws/data/metaworld/with-depth/handle-pull.hdf5
  mode: overwrite
  compression: null
metaworld:
  benchmark_id: Meta-World/MT1
  env_name: handle-pull-v3
  seed: 0
  max_steps: 450
  terminate_on_success: true
render:
  height: 128
  width: 128
  save_depth: true
  lookat:
  - 0.0
  - 0.6
  - 0.0
  up:
  - 0.0
  - 0.0
  - 1.0
  cameras:
    - name: cam0
      r: 0.8
      theta: -45.0
      phi: 0.0
      fovy: 45.0
    - name: cam1
      r: 0.8
      theta: -45.0       
      phi: 180.0          
      fovy: 45.0
    - name: cam2
      r: 0.8
      theta: -60.0        
      phi: -30.0             
      fovy: 45.0
    - name: cam3
      r: 0.8
      theta: -60.0         
      phi: 210.0           
      fovy: 45.0
    - name: cam4
      r: 0.8
      theta: -30.0       
      phi: 45.0          
      fovy: 45.0
    - name: cam5
      r: 0.8
      theta: -30.0     
      phi: 135.0            
      fovy: 45.0
segmentation:
  enabled: false
  save_objtype: false
policies:
  scripted:
    enabled: true
    num_demos: 400
    policy_class: null
visualize:
  enabled: false
  show_window: false
  every_n_steps: 1
  ncols: 3
  pad: 4
  window_name: metaworld demos (top=RGB, bottom=SEG)
  stop_key: q
  save_video_dir: null
  video_fps: 10.0
dino:
  enabled: false
  model: dinov2_vitb14
  image_size: 224
  batch_size: 256
  device: cuda
  dtype: float16
