seed: 42
device: cuda

wandb:
  enabled: true
  project: metaworld-window-open-DrQv2
  name: SinCro_seed42

env:
  benchmark_id: Meta-World/MT1
  env_name: window-open
  image_height: 128
  image_width: 128
  frame_stack: 3
  action_repeat: 2
  max_episode_steps: 250

  cameras:
    - name: cam0
      r: 0.8
      theta: -30.0
      phi: -30.0
      fovy: 45.0
    - name: cam1
      r: 0.8
      theta: -30.0         
      phi: 0.0             
      fovy: 45.0
    - name: cam2
      r: 0.8
      theta: -30.0       
      phi: 30.0          
      fovy: 45.0
    - name: cam3
      r: 0.8
      theta: -45.0        
      phi: -30.0          
      fovy: 45.0
    - name: cam4
      r: 0.8
      theta: -45.0         
      phi: 0.0            
      fovy: 45.0
    - name: cam5
      r: 0.8
      theta: -45.0     
      phi: 30.0            
      fovy: 45.0


  lookat: [0.0, 0.6, 0.0]
  up: [0.0, 0.0, 1.0]

vision:
  encoder_type: sincro
  img_height: 128
  img_width: 128

  sincro:
    checkpoint_path: ./checkpoints/metaworld/encoders/SinCro/window_open/step_00300000_encoder.tar

    img_size: 128
    netdepth: 8
    netwidth: 256
    netdepth_fine: 8
    netwidth_fine: 256
    N_rand: 1024
    N_samples: 64
    N_importance: 128
    multires: 10
    multires_views: 4
    i_embed: 0
    use_viewdirs: true
    raw_noise_std: 0.0
    white_bkgd: false
    perturb: 1.0
    lindisp: false

    patch_size: 16
    embed_dim: 256
    vit_depth: 4
    vit_num_heads: 4
    vit_mlp_dim: 1024
    decoder_depth: 2
    decoder_num_heads: 2
    decoder_mlp_dim: 1024
    decoder_output_dim: 256

    time_interval: 3
    mask_ratio: 0.75
    num_views: 6

    near: 0.1
    far: 2.5
    chunk: 32768

    pool: flatten

agent:
  lr: 1.0e-4
  feature_dim: 50
  hidden_dim: 1024
  critic_target_tau: 0.01

  # DrM-specific knobs
  dormant_threshold: 0.025
  target_dormant_ratio: 0.20
  dormant_temp: 10.0
  target_lambda: 0.70
  lambda_temp: 50.0
  dormant_perturb_interval: 100000
  min_perturb_factor: 0.20
  max_perturb_factor: 0.95
  perturb_rate: 2.0

  stddev_type: awake
  stddev_schedule: linear(1.0,0.1,100000)
  stddev_clip: 0.3
  expectile: 0.9

train:
  num_train_steps: 1000000
  seed_steps: 4000
  batch_size: 256
  replay_size: 100000
  update_every_steps: 2
  gradient_steps: 3
  discount: 0.99

  replay_dir: ./buffer/metaworld/window_open/sincro/seed42/
  replay_num_workers: 4
  replay_fetch_every: 1000
  save_replay_snapshot: false
  nstep: 3

  log_every_steps: 1000
  eval_every_steps: 10000
  num_eval_episodes: 100
  rolling_window: 10

  checkpoint_every_steps: 50000
  checkpoint_dir: ./checkpoints/metaworld/policies/drqv2/sincro/window_open/seed42/

visualization:
  enabled: false
  window_name: metaworld_window_open_drqv2
  wait_key: 1
  scale: 1.0

