seed: 98
device: cuda
wandb:
  enabled: true
  project: metaworld-button-press-wall-DrQv2
  name: SplatterVAE-t0-reconstruction-independent-frames
  tags:
  - single-timestep-ablation
  - independent-frame-policy
  - embed-dim-128
env:
  benchmark_id: Meta-World/MT1
  env_name: button-press-wall
  image_height: 128
  image_width: 128
  frame_stack: 3
  action_repeat: 2
  max_episode_steps: 250
  cameras:
  - name: cam0
    r: 1.0
    theta: 45.0
    phi: 0.0
    fovy: 45.0
  - name: cam1
    r: 1.0
    theta: 45.0
    phi: 180.0
    fovy: 45.0
  - name: cam2
    r: 1.0
    theta: 60.0
    phi: -30.0
    fovy: 45.0
  - name: cam3
    r: 1.0
    theta: 60.0
    phi: 210.0
    fovy: 45.0
  - name: cam4
    r: 1.0
    theta: 30.0
    phi: 30.0
    fovy: 45.0
  - name: cam5
    r: 1.0
    theta: 30.0
    phi: 150.0
    fovy: 45.0
  lookat:
  - 0.0
  - 0.6
  - 0.0
  up:
  - 0.0
  - 0.0
  - 1.0
vision:
  encoder_type: splatter_vae
  img_height: 128
  img_width: 128
  vit:
    patch_size: 16
    in_chans: 3
    embed_dim: 128
    depth: 8
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: true
    dropout: 0.0
    attn_dropout: 0.0
    drop_path_rate: 0.1
    layerscale_init: 1.0
  splatter_vae:
    checkpoint_path: ./checkpoints/metaworld/encoders/SplatterVAE-single-timestep/button-press-wall/grouped-gaussian-set/step_00380000.pth
    max_sh_degree: 1
    model:
      state_dim: 256
      temporal_modeling: false
      masking:
        inv_tube_mask_ratio: 0.5
        tube_mask_per_view: true
        flow_patch_threshold_pixels: 0.5
      decoder:
        num_parent_tokens: 256
        gaussians_per_parent: 8
        dim: 128
        depth: 2
        num_heads: 4
        mlp_ratio: 4.0
      motion:
        translation_max: 0.5
agent:
  lr: 0.0001
  feature_dim: 256
  hidden_dim: 1024
  augment_pixels: false
  critic_target_tau: 0.01
  stddev_schedule: linear(1.0,0.1,150000)
  stddev_clip: 0.3
train:
  num_train_steps: 1000000
  seed_steps: 4000
  batch_size: 256
  replay_size: 1000000
  update_every_steps: 2
  gradient_steps: 1
  discount: 0.99
  replay_dir: ./buffer/metaworld/button-press-wall/splattervae_single_timestep_ablation/seed98/
  replay_num_workers: 1
  nstep: 3
  log_every_steps: 1000
  eval_every_steps: 10000
  num_eval_episodes: 120
  rolling_window: 10
  checkpoint_every_steps: 50000
  checkpoint_dir: ./checkpoints/metaworld/policies/drqv2/splattervae_single_timestep_ablation/button-press-wall/seed98/
visualization:
  enabled: false
  window_name: metaworld_button-press-wall_drqv2
  wait_key: 1
  scale: 1.0
